'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { fmtDate } from '@/lib/format';

export function StlPanel({ projectId, assets, frozen }:
  { projectId: string; assets: { id: string; name: string; prompt: string; status: string; createdAt: Date }[]; frozen: boolean }) {
  const [name, setName] = useState('');
  const [prompt, setPrompt] = useState('');
  const [busy, startTransition] = useTransition();
  const router = useRouter();
  function submit() {
    if (!name.trim() || !prompt.trim()) return;
    startTransition(async () => {
      await fetch('/api/stl/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ projectId, name, prompt }) });
      setName(''); setPrompt('');
      router.refresh();
    });
  }
  return (
    <div className="grid md:grid-cols-2 gap-6">
      <div>
        <h3 className="font-semibold mb-2">Describe your part</h3>
        <input className="input mb-2" placeholder="Part name (e.g. brachistochrone-slide-cycloid)"
          disabled={frozen} value={name} onChange={e => setName(e.target.value)} />
        <textarea className="input font-mono text-sm" rows={6}
          disabled={frozen} value={prompt} onChange={e => setPrompt(e.target.value)}
          placeholder="e.g. A 400mm long, 40mm wide brachistochrone slide following a cycloid curve generated by a rolling circle of radius 70mm. 6mm channel for a 12mm steel ball. M3 mounting tabs at each end." />
        <button disabled={frozen || busy} onClick={submit} className="btn-primary mt-2">{busy ? 'Generating…' : 'Generate STL'}</button>
        <p className="text-xs text-slate-500 mt-2">
          ⚠ STL generation is in preview. The current version queues a placeholder file and records your prompt.
          Real AI → OpenSCAD → STL rendering is coming soon.
        </p>
      </div>

      <div>
        <h3 className="font-semibold mb-2">Generated parts</h3>
        {assets.length === 0 ? (
          <p className="text-sm text-slate-500">No parts yet.</p>
        ) : (
          <ul className="space-y-2">
            {assets.map(a => (
              <li key={a.id} className="border rounded p-3 text-sm">
                <div className="flex items-center justify-between">
                  <div className="font-medium">{a.name}</div>
                  <span className="text-xs px-2 py-0.5 bg-amber-50 text-amber-700 rounded border border-amber-200">{a.status}</span>
                </div>
                <div className="text-xs text-slate-500 mt-1">{fmtDate(a.createdAt)}</div>
                <p className="text-xs text-slate-600 mt-1 line-clamp-3">{a.prompt}</p>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
